"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
$git_branch\
${custom.git_age}\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$swift\
$ruby\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "main"

[directory]
style = "bold fg:dark_blue"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Developer" = "Developer "
"Documents" = "Documents 󰈙"
"Downloads" = "Downloads "
"Music" = "Music "
"Pictures" = "Pictures "

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](white)'

[git_branch]
style = "fg:green"
symbol = " "
format = "[on](white) [$symbol$branch ]($style)"

[custom.git_age]
command = "\"$DOTFILES/bin/starship-git-prompt\""
description = "Git status and time since last git commit"
format = "$output "
require_repo = true
shell = ["/bin/zsh", "--no-rcs"]
unsafe_no_escape = true
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"

[fill]
symbol = " "

[python]
style = "teal"
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ""

[lua]
format = '[$symbol($version )]($style)'
symbol = ' '

[nodejs]
style = "blue"
symbol = " "

[golang]
style = "blue"
symbol = " "

[haskell]
style = "blue"
symbol = " "

[rust]
style = "orange"
symbol = " "

[swift]
style = "orange"
symbol = " "

[ruby]
style = "blue"
symbol = " "

[package]
symbol = "󰏗 "

[aws]
symbol = " "
style = "yellow"
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = " "
style = "fg:#06969A"
format = '[$symbol]($style) $path'
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_extensions = ["Dockerfile"]

[jobs]
symbol = " "
style = "red"
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = "fg:gray"
format = '[$duration]($style)'

[palettes.main]
dark_blue = "#61afef"
blue = "#56b6c2"
red = "#e06c75"
green = "#98c379"
purple = "#c678dd"
cyan = "#56b6c2"
orange = "#be5046"
yellow = "#e5c07b"
gray = "#828997"
white = "#abb2bf"
black = "#2c323c"
