local pick = require("mini.pick")
pick.setup()
vim.keymap.set("n", "<leader>pf", pick.builtin.files, { desc = "Find files" })
vim.keymap.set("n", "<leader>ps", function()
  pick.builtin.grep({ pattern = vim.fn.expand("<cword>") })
end, { desc = "Search word under cursor" })
vim.keymap.set("n", "<leader>pg", pick.builtin.grep_live, { desc = "Search project text" })
vim.keymap.set("n", "<leader>vh", pick.builtin.help, { desc = "Search help" })

local extra = require("mini.extra")
extra.setup()
vim.keymap.set("n", "<leader>xx", extra.pickers.diagnostic, { desc = "Search diagnostics" })
vim.keymap.set("n", "<leader>pk", extra.pickers.keymaps, { desc = "Search keymaps" })
